version: '3.3'
services:
  web:
    container_name: geodrilling
    image: geodrilling:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/geodrilling
      - SPRING_DATASOURCE_USERNAME=geodrilling
      - SPRING_DATASOURCE_PASSWORD=wkhhr1ve
  db:
    image: postgres
    environment:
      POSTGRES_USER: geodrilling
      POSTGRES_PASSWORD: wkhhr1ve
    ports:
      - "5432:5432"

